#!/usr/bin/env node
/**
 * Regenerate `src/abi/generated.ts` from `../shared/abis/*.json`.
 *
 * `shared/` is the monorepo's single source of truth for ABIs, but the keeper must be buildable
 * from the `backend/` directory alone (the Docker build context is `backend/`), so the generated
 * TypeScript is committed. Re-run `pnpm run sync-abis` whenever the contracts change.
 *
 * Only the entries the keeper actually uses are emitted — a narrow ABI keeps viem's type
 * inference fast and makes accidental use of owner-only functions a compile error.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sharedAbis = resolve(here, '../../shared/abis');
const outFile = resolve(here, '../src/abi/generated.ts');

/** Sentinel usable in `keep`: retain every `type: "error"` member. */
const ALL_ERRORS = '*errors';

/**
 * Exported const name -> { file, keep } where `keep` lists the ABI members to retain.
 * `keep` entries are matched on `name` (errors/events/functions alike).
 */
const SELECTION = [
  {
    exportName: 'vaultAbi',
    file: 'PoolmigoVaultUpgradeable.json',
    keep: [
      // keeper-callable
      'deployTo',
      'rebalance',
      // views the keeper reads
      'tokens',
      'totalTokens',
      'adapters',
      'adapterCount',
      'isKeeper',
      'isAdapter',
      'isToken',
      'rebalancePaused',
      'performanceFeeBps',
      'treasury',
      'balanceOf',
      'totalSupply',
      // events the keeper decodes from its own receipts
      'Deployed',
      'Rebalanced',
      'PerformanceFeeAccrued',
      // every custom error, so failures decode to a readable name
      ALL_ERRORS,
    ],
  },
  {
    exportName: 'positionAdapterAbi',
    file: 'IPositionAdapter.json',
    keep: ['position', 'dex', 'poolId'],
  },
  {
    exportName: 'erc20Abi',
    file: 'MockToken.json',
    keep: ['balanceOf', 'allowance', 'totalSupply'],
  },
  {
    // Test-only helper: `simulateFees` is permissionless on the local mock adapter and is used by
    // the integration tests to seed harvestable fees. Never called by the keeper itself.
    exportName: 'mockAdapterTestAbi',
    file: 'MockPositionAdapter.json',
    keep: ['simulateFees', 'deployed', 'harvestable', 'position'],
  },
];

function selectMembers(abi, keep) {
  const wantsAllErrors = keep.includes(ALL_ERRORS);
  const names = new Set(keep.filter((k) => k !== ALL_ERRORS));
  return abi.filter((m) => {
    if (m.type === 'error' && wantsAllErrors) return true;
    return typeof m.name === 'string' && names.has(m.name);
  });
}

const chunks = [
  '// AUTO-GENERATED by `pnpm run sync-abis` from ../../shared/abis/*.json — do not edit by hand.',
  '// shared/abis is the monorepo source of truth; this file is committed so that `backend/`',
  '// builds standalone (Docker build context is `backend/`).',
  '',
];

for (const { exportName, file, keep } of SELECTION) {
  const abi = JSON.parse(readFileSync(resolve(sharedAbis, file), 'utf8'));
  const picked = selectMembers(abi, keep);
  if (picked.length === 0) throw new Error(`no ABI members selected from ${file}`);
  chunks.push(`/** Selected from shared/abis/${file}. */`);
  chunks.push(`export const ${exportName} = ${JSON.stringify(picked, null, 2)} as const;`);
  chunks.push('');
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, chunks.join('\n'));
console.log(`wrote ${outFile}`);
for (const { exportName, file } of SELECTION) console.log(`  ${exportName} <- ${file}`);
