// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

/**
 * @title PoolmigoCreate3
 * @notice Minimal CREATE3 factory: deploys any contract to an address that depends only on
 *         (this factory's address, salt) — not on the deployed bytecode, its constructor args,
 *         the caller, or the caller's nonce. That is what lets the same contract live at the
 *         same address on every chain where this factory itself sits at the same address.
 *
 * Mechanism:
 *   1. `deploy()` CREATE2-deploys one `Create3Dispatcher` per salt. The dispatcher's creation
 *      code is a compile-time constant (no constructor args), so its CREATE2 address is a pure
 *      function of (factory, salt).
 *   2. `deploy()` then calls the dispatcher with the target's creation code. The dispatcher
 *      CREATEs it — its first CREATE, nonce 1 — so the target lands at
 *      `keccak(rlp([dispatcher, 1]))`, independent of what is being deployed.
 *
 * Operating rules (see script/DeployDeterministic.s.sol + script/deterministic-address-check.sh):
 *   - Deploy this factory ONCE per chain at the SAME address (e.g. as the first transaction of a
 *     dedicated deployer account; or via a canonical deterministic CREATE2 deployer if the chain
 *     has one). Future chains: same drill.
 *   - Salt discipline: one documented salt per logical contract (`keccak256("poolmigo.vault.v1")`).
 *     Never reuse a salt for different bytecode — the address does not commit to the code it holds.
 *   - An initializer invoked from inside the constructor of a CREATE3-deployed contract runs with
 *     `msg.sender == dispatcher`. `PoolmigoVaultUpgradeable.initialize` takes explicit addresses,
 *     so the atomic deploy+initialize path is safe; keep it that way.
 *   - Do NOT edit this file after a factory is deployed at an address shared across chains: a
 *     different dispatcher creation code would predict different addresses for that factory.
 */
contract PoolmigoCreate3 {
    error Create3__SaltAlreadyUsed(address dispatcher);
    error Create3__AddressMismatch(address predicted, address actual);

    /// @notice Deploys `creationCode` at {create3Address}(salt). Reverts if the salt was used.
    function deploy(bytes32 salt, bytes memory creationCode) external payable returns (address deployed) {
        if (dispatcherAddress(salt).code.length != 0) revert Create3__SaltAlreadyUsed(dispatcherAddress(salt));
        Create3Dispatcher dispatcher = new Create3Dispatcher{salt: salt}();
        deployed = dispatcher.dispatch{value: msg.value}(creationCode);
        address predicted = create3Address(salt);
        if (deployed != predicted) revert Create3__AddressMismatch(predicted, deployed);
    }

    /// @notice The address `deploy(salt, ...)` lands on, for any creation code.
    function create3Address(bytes32 salt) public view returns (address) {
        address dispatcher = dispatcherAddress(salt);
        return
            address(uint160(uint256(keccak256(abi.encodePacked(bytes1(0xd6), bytes1(0x94), dispatcher, bytes1(0x01))))));
    }

    /// @notice The intermediary dispatcher's CREATE2 address for `salt`.
    function dispatcherAddress(bytes32 salt) public view returns (address) {
        return address(
            uint160(
                uint256(
                    keccak256(
                        abi.encodePacked(
                            bytes1(0xff), address(this), salt, keccak256(type(Create3Dispatcher).creationCode)
                        )
                    )
                )
            )
        );
    }
}

/**
 * @dev Implementation detail of {PoolmigoCreate3}: created per salt via CREATE2, then called once
 *      with the target's creation code. Its first CREATE uses nonce 1 — the fixed point CREATE3
 *      relies on. Not intended for direct use.
 */
contract Create3Dispatcher {
    error Create3Dispatcher__Unauthorized();
    error Create3Dispatcher__CreateFailed();

    address public immutable factory;

    constructor() {
        factory = msg.sender;
    }

    /// @dev Bubbles the target constructor's revert data on failure.
    ///      NOTE: CREATE reads init code from *memory* — a calldata pointer would be silently
    ///      reinterpreted as a memory offset (deploying an empty contract). Hence the copy.
    function dispatch(bytes calldata creationCode) external payable returns (address deployed) {
        if (msg.sender != factory) revert Create3Dispatcher__Unauthorized();
        bytes memory code = creationCode;
        assembly ("memory-safe") {
            deployed := create(callvalue(), add(code, 0x20), mload(code))
        }
        if (deployed == address(0)) {
            assembly {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
        }
    }
}
